### ISSUE TITLE
Is ropensci/software-review hard-coded somewhere

### ISSUE THREAD

**Issue by maelle** [ropensci-org/buffy#62] opened 2022-02-11 11:23 UTC
I opened an issue in https://github.com/ropenscilabs/statistical-software-review/issues/30

provoking a response in https://github.com/ropensci/software-review/issues/30

**Comment by maelle** [comment] 2022-02-11 11:24
Pinging @xuanxu @mpadge

**Comment by maelle** [comment] 2022-02-11 11:25
ah yes! https://github.com/ropensci-org/buffy/blob/a61112d8de7ae2fa0e08d1896a8a6c175a54c58e/config/settings-production.yml#L33

**Comment by maelle** [comment] 2022-02-11 11:25
Could the repo be filled by buffy instead, based on the info in the webhook payloads?

**Comment by maelle** [comment] 2022-02-11 11:26
So maybe for the test repo I should use... the testing config :grin:

**Comment by xuanxu** [comment] 2022-02-11 11:42
The [current config](https://github.com/ropensci-org/buffy/blob/ropensci/config/settings-production.yml#L28-L37) for that external call is:
```yaml
external_service:
        name: editorcheck
        url: http://138.68.123.59:8000/editorcheck
        method: get
        query_params:
          repo: ropensci/software-review
        data_from_issue:
          - repourl
          - issue_id
        template_file: goodpractice.md
```

That seems wrong because the repo is being hardcoded but also the `repourl` is an invalid key for [data_from_issue](https://buffy-ropensci.readthedocs.io/en/latest/responders/external_service.html#params), so I think that config is calling the following url: 
`http://138.68.123.59:8000/editorcheck?repo=ropensci/software-review&repourl=&issue_id=23`

But I guess what needs to be called is: 
`http://138.68.123.59:8000/editorcheck?repo=ropensci/software-review&issue_id=23` 
with both `repo` and `issue_id` extracted dinamically. So, the config should be simplyfied to:

```yaml
external_service:
        name: editorcheck
        url: http://138.68.123.59:8000/editorcheck
        method: get
        data_from_issue:
          - repo
          - issue_id
        template_file: goodpractice.md
```

**Comment by mpadge** [comment] 2022-02-14 00:36
Thanks for the help @xuanxu. Before i commit the fix, can you please clarify your statement that:
> the repourl is an invalid key for data_from_issue

?
`data_from_issue` will pick up any and all html variables encoded in the issue body, right? We use `repourl` to define the URL of the repo being reviewed, as encoded in [our templates here](https://github.com/ropensci/software-review/blob/aa15193af42613ad25d678f2347ab92c123e1613/.github/ISSUE_TEMPLATE/A-submit-software-for-review.md?plain=1#L14). That is picked up and passed on to our external service. That means your suggested version with:
``` yaml
    data_from_issue:
      - repo
```
should actually revert to the current form of
``` yaml
    data_from_issue:
      - repourl
```
We use `repo` to define the point from which the call to buffy originates, and `repourl` to define the URL of the repository which is being reviewed. The problem is that `repo` is currently hard-coded as `ropensci/software-review`, but could also be anywhere else that our bot is currently watching. A current request passed on to our external service looks like this:
```
http://138.68.123.59:8000/editorcheck?issue_id=30&repo=ropensci%2Fsoftware-review&repourl=https%3A%2F%2Fgithub.com%2Fropensci%2Friem
```
The only thing that should change is that the formerly hard-coded `repo=ropensci%2Fsoftware-review` should be dynamically picked up from wherever it is called, but `repourl` should remain as is. Can you please clarify whether `repo` will simply be dynamically detected and passed on to the external call, or whether we need to include:
``` yaml
    data_from_issue:
      - repo
      - repourl
```
I don't think those lines are correct, because `repo` is not encoded as a HTML variable, so won't be detected as `data_from_issue`. Can you please clarify how `repo` is, or can be, dynamically detected, and how we can ensure that it is passed on to the external service? Thanks :+1:

**Comment by xuanxu** [comment] 2022-02-14 16:53
Oh! you are right @mpadge, sorry: I read the code too fast and thought you were trying to get the repository using `repourl` instead of `repo`, but `repourl` is a html variable encoded in the issue, so it's totally correcto to use it in `data_from_issue`.

About the use of `repo` to define the point from which the call to buffy originates: there are some metadata about the issue you can get from data_from_issue without need to html-encode it in the issue's text. One of them is repo. This is the complete list:  `issue_id`, `issue_author`, `repo`, `sender` and `bot_name`

So yeah you can get all the info you need for the external call with:
```yaml
data_from_issue:
          - issue_id
          - repo
          - repourl
```

**Comment by mpadge** [comment] 2022-02-15 03:22
Awesome, thanks @xuanxu! I'll close this issue via PR soon

**Comment by maelle** [comment] 2022-06-21 12:37
@mpadge can you please confirm that this issue can be closed? Thank you!

**Comment by mpadge** [comment] 2022-06-21 12:59
Yep, closed via https://github.com/ropensci-org/buffy/commit/d2bbc7d76e62e2814d2b6f51910a203fbf6ffc7b

**Closed as completed by mpadge** 2022-06-21 12:59 UTC
